name: Feature request
description: Proposer une amelioration
labels: [enhancement]
body:
  - type: textarea
    id: need
    attributes:
      label: Besoin
      description: Quel probleme veux-tu resoudre
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposition
      description: Quelle solution proposes-tu
    validations:
      required: true
